name: Greeting from YUEN Chi Ching
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chi Ching
        MIDDLE_NAME: \,
        LAST_NAME: Yuen
      run:
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.